version: "3.8"
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8099:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,LOCAL_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "BROKER://kafka:29092,LOCAL_HOST://localhost:9092"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_server.conf"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "BROKER://kafka:29092,CONTROLLER://kafka:29093,LOCAL_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
#      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#      KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      KAFKA_SUPER_USERS: "User:admin"
    volumes:
      - ./scripts/run.sh:/tmp/run.sh
    command: >
      bash -c 'if [ ! -f /tmp/run.sh ]; then 
               echo "ERROR: Did you forget the run.sh file that came with this docker-compose.yml file?" && exit 1; 
               else /tmp/run.sh && /etc/confluent/docker/run; 
               fi'

  kafka-topic-creator:
    image: confluentinc/cp-kafka:7.2.1
    volumes:
      - ./data/events.txt:/data/events.txt
    depends_on:
      - kafka
    command: >
      bash -c 'echo Waiting for Kafka to be ready... &&
               cub kafka-ready -b kafka:29092 1 30 &&
               kafka-topics --create --topic event.created --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092  &&
               kafka-topics --create --topic event.dispatched --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 &&
               kafka-console-producer --bootstrap-server kafka:29092 --property parse.key=false -topic event.created < /data/events.txt'
